from django import forms

class LungCancerForm(forms.Form):
    age = forms.IntegerField(label="Age")
    gender = forms.ChoiceField(choices=[('1', 'Male'), ('2', 'Female')])
    air_pollution = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    alcohol_use = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    dust_allergy = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    occupational_hazards = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    genetic_risk = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    chronic_lung_disease = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    balanced_diet = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    obesity = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    smoking = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    passive_smoker = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    chest_pain = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    coughing_of_blood = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    fatigue = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    weight_loss = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    shortness_of_breath = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    wheezing = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    swallowing_difficulty = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    clubbing_of_finger_nails = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    frequent_colds = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    dry_cough = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
    snoring = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 9)])
